---
- name: Install php and deps
  become: yes
  package: name="{{item}}" state=present
  with_flattened: "{{php_packages}}"
  when: phase == "building"

- name: Copy php.ini configuration
  become: yes
  template:
    src: php.ini
    dest: /etc/php.d/phabricator.ini
# TODO      notify: start httpd
