---
- name: add repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/tflink/phabricator/repo/epel-7/"{{item}}"
    dest: /etc/yum.repos.d/{{item}}
  with_items: "tflink-phabricator-epel-7.repo"
  # yum_repository:
  #   name: phabricator
  #   description: Copr repo for phabricator owned by tflink
  #   baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  #   gpgkey: https://copr-be.cloud.fedoraproject.org/results/tflink/phabricator/pubkey.gpgll
    # password: "$6$.nd53PkO$GuYKTpQQjtc.S35Rrp3xU1x0SetDU8nCDnT.0CMjuiqr6kiotkYeDkZHtE799qPxMHJeTf/Y9IHy7RRHmRhia/"
    # update_password: always


- name: add phd group
  group:
    name: phd
    state: present

- name: add user phd
  become: yes
  user:
    name: phd
    groups: phd,apache
    system: yes

- name: add user git
  become: yes
  user:
    name: git
    system: yes
    # shell: /sbin/nologin
    # password: "NP"
    # update_password: always

- name: Clone libphutil
  become: yes
  git:
    repo: https://github.com/phacility/libphutil
    dest: /srv/www/libphutil
    version: stable
    depth: 1

- name: Clone arcanist
  become: yes
  git:
    repo: https://github.com/phacility/arcanist
    dest: /srv/www/arcanist
    version: stable
    depth: 1

- name: set /srv/www permissions
  become: yes
  file:
    path: /srv/www

    group: phd
    mode: 0775

- name: Clone phabricator
  become: yes
  become_user: phd
  git:
    repo: https://github.com/phacility/phabricator
    dest: "{{ phabricator_path }}"
    version: stable
    depth: 1

- name: Place phabricator config
  become: yes
  become_user: phd
  template:
    src: myconfig.conf.php
    dest: "{{ phabricator_path }}conf/default.conf.php"

- name: Migrate the database
  become: yes
  become_user: phd
  command: chdir={{ phabricator_path }} ./bin/storage upgrade --force
  when: phase == "running"

- name: Create the repository directory
  become: yes
  file:
    path: "{{ repositories_path }}"
    owner: phd
    group: phd
    state: directory

# - name: copy phd init script
#   sudo: yes
#   template:
#     src: phd.j2
#     dest: /etc/init.d/phd
#     owner: root
#     group: root
#     mode: 0755

- name: run phd and enable autostart
  become: yes
  supervisorctl:
    name: phabricator-phd
    state: started
    # enabled: yes
  when: phase == "running"
