---
- name: Install php and deps
  become: yes
  package:
    name: "{{ item.name }}"
    state: present
  with_items: "{{php_packages}}"

- name: Copy php.ini configuration
  become: yes
  template:
    src: php.ini
    dest: /etc/php.d/phabricator.ini
  notify: restart httpd
