---
- name: ensure httpd is enabled
  template:
    src: httpd.ini.j2
    dest: /etc/supervisord.d/httpd.ini
    owner: root
    group: root
    mode: 0755

# - name: ensure httpd is present
#   yum:
#     name: httpd
#     state: present
#   when: phase == "running"

# # apply only when docker run to set domain variable only when we setup container
# # (not image)
# - name: Copy httpd config
#   become: yes
#   template:
#     src: httpd.ini.j2
#     dest: /etc/httpd/conf.d/httpd.ini
#   notify:
#     - start httpd
#   when: phase == "running"



# - name: ensure httpd is enabled
#   service:
#     name: httpd
#     enabled: yes
