---
- name: ensure httpd is enabled
  template:
    src: httpd.ini.j2
    dest: /etc/supervisord.d/httpd.ini
    owner: root
    group: root
    mode: 0755

# - name: ensure httpd is present
#   yum:
#     name: httpd
#     state: present
#   when: phase == "running"

- name: Copy httpd config
  become: yes
  template:
    src: phabricator.conf.j2
    dest: /etc/httpd/conf.d/phabricator.conf
  notify:
    - start httpd
  when: phase == "running"

- name: Copy httpd config
  become: yes
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
  notify:
    - start httpd
  when: phase == "building"





# - name: ensure httpd is enabled
#   service:
#     name: httpd
#     enabled: yes
