php_packages:
  - php
  - php-mysql
  - php-gd
  - php-cli
  - php-process
  - php-devel
  - php-pecl-apc
  - php-pecl-json
  - php-mbstring

# See : https://github.com/phacility/phabricator/blob/master/scripts/install/install_rhel-derivs.sh
