---
- name: Install MySQL package
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - mariadb-server

- name: Create MySQL configuration file
  become: yes
  template:
    src: my.cnf
    dest: /etc/my.cnf
  notify:
  - restart mysql
  when: phase=="running"

- name: enable MySQL Service
  become: yes
  service:
    name: mysql
    # state: started
    enabled: true
  notify:
  - restart mysql
