---

# {% if grains['os_family'] == 'RedHat' %} ohai_init_package": "systemd"

#    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ohai_init_package == "systemd") or
#           (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")
- name: add repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/tflink/phabricator/repo/epel-7/"{{item}}"
    dest: /etc/yum.repos.d/{{item}}
  with_items: "tflink-phabricator-epel-7.repo"
  when: phase == "building"
  # yum_repository:
  #   name: phabricator
  #   description: Copr repo for phabricator owned by tflink
  #   baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  #   gpgkey: https://copr-be.cloud.fedoraproject.org/results/tflink/phabricator/pubkey.gpgll
    # password: "$6$.nd53PkO$GuYKTpQQjtc.S35Rrp3xU1x0SetDU8nCDnT.0CMjuiqr6kiotkYeDkZHtE799qPxMHJeTf/Y9IHy7RRHmRhia/"
    # update_password: always


- name: Install phd init script
  become: yes
  template:
    src: phd.ini.j2
    dest: /etc/supervisord.d/phabricator-phd.ini
    owner: root
    group: root
    mode: 0755
  when: phase == "building"


- name: Install phabricator deamons manager
  become: yes
  template:
    src: phabricator-deamon-mgr.sh.j2
    dest: /usr/local/bin/phabricator-deamon-mgr.sh
    owner: root
    group: root
    mode: 0755
  when: phase == "building"

- name: add phd group
  group:
    name: phd
    state: present
  when: phase == "building"

- name: add user phd
  user:
    name: phd
    groups: phd,apache
    system: yes
  when: phase == "building"

- name: add user git
  user:
    name: git
    system: yes
    # shell: /sbin/nologin
    # password: "NP"
    # update_password: always
  when: phase == "building"

- name: Clone libphutil
  git:
    repo: https://github.com/phacility/libphutil
    dest: /srv/www/libphutil
    version: stable
    depth: 1
  async: 45
  when: phase == "building"


- name: Clone arcanist
  git:
    repo: https://github.com/phacility/arcanist
    dest: /srv/www/arcanist
    version: stable
    depth: 1
  async: 45
  when: phase == "building"

- name: set /srv/www permissions
  become: yes
  file:
    path: /srv/www
    group: phd
    mode: 0775
  when: phase == "building"

- name: Clone phabricator
  become: yes
  become_user: phd
  git:
    repo: https://github.com/phacility/phabricator
    dest: "{{ phabricator_path }}"
    version: stable
    depth: 1
  when: phase == "building"

# - name: Selecting default.conf.php as Configuration File
#   lineinfile:
#     dest: "{{ phabricator_path }}conf/local/ENVIRONMENT"
#     line: "default"
#     state: present
#     create: yes
#   when: phase == "building"

- name: Configure phabricator
  command: "bin/config set {{ item.key }} {{ item.value }} "
  args:
    chdir: "{{ phabricator_path }}"
  with_dict:
    "{{ phabricator_conf }}"
  when: phase == "building"

- name: Create the pid directory
  become: yes
  file:
    path: "/var/tmp/phd/pid"
    owner: phd
    group: phd
    state: directory
  when: phase == "building"

- name: Create the log directory
  become: yes
  file:
    path: "/var/tmp/phd/log"
    owner: phd
    group: phd
    state: directory
  when: phase == "building"

- name: Create the repository directory
  become: yes
  file:
    path: "{{ repositories_path }}"
    owner: phd
    group: phd
    state: directory
  when: phase == "building"

# - name: Configure phabricator
#   command :  bin/config.sh set "{{ item.key }} {{ item.value }}"
#  # {{ item.value.categories.key }}.{{ item.value.categories.key.value }}
#   args:
#     chdir: "{{ phabricator_path }}"
#   with_dict:
#     "{{ phabricator_conf }}"



# # (must be load during run time)
# - name: Place phabricator config
#   become: yes
#   become_user: phd
#   template:
#     src: myconfig.conf.php.j2
#     dest: "{{ phabricator_path }}conf/default.conf.php"
#   when: phase == "running"

# - debug: var=phabricator_conf

- name: wait for mysql
  wait_for:
    port: 3306
    host: "{{ phabricator_conf['mysql.host'] }}"
  when: phase == "running"


- name: Migrate the database
  become: yes
  become_user: phd
  command: chdir={{ phabricator_path }} ./bin/storage upgrade --force
  when: phase == "running"



# - name: run phd
#   become: yes
#   become_user: phd
#   command: bin/phd start
#   args:
#     chdir: "{{ phabricator_path }}"
#   when: phase == "running"


# - name: copy phd init script
#   become: yes
#   template:
#     src: phd.j2
#     dest: /etc/init.d/phd
#     owner: root
#     group: root
#     mode: 0755


# - name: copy phabricator init script
#   become: yes
#   template:
#     src: phabricator.ini.j2
#     dest: /etc/supervisord.d/phabricator-phd.ini
#     owner: root
#     group: root
#     mode: 0755


# - name: run phd and enable autostart
#   become: yes
#   supervisorctl:
#     name: phabricator-phd
#     state: started
#     # enabled: yes
#   when: phase == "running"



- name: start phd
  become: yes
  supervisorctl:
    name: phd
    state: started
  when: phase == "running"
