---
- name: ensure apache is at the latest version
  yum:
    name: httpd
    state: present
  notify:
    - restart httpd

# apply only when docker run to set domain variable only when we setup container
# (not image)
- name: Copy httpd config
  become: yes
  template:
    src: phabricator.conf.ini
    dest: /etc/httpd/conf.d/phabricator.conf
  notify:
    - restart httpd
  when: phase == "running"

# - name: ensure httpd is enabled
#   service:
#     name: httpd
#     enabled: yes

- name: ensure httpd is enabled
  become: yes
  template:
    src: httpd.ini.j2
    dest: /etc/supervisord.d/httpd.ini.j2
    owner: root
    group: root
    mode: 0755
