---
- name: install
  package: name="{{item}}" state=present
  with_flattened:
    - git
    - sudo
    - openssh-server

# TODO : configure host on boot
# - name: Add alias to 127.0.0.1 to /etc/hosts
#   sudo: yes
#   lineinfile:
#     dest: /etc/hosts
#     regexp: "^127.0.0.1 {{ domain }}"
#     line: "127.0.0.1 {{ domain }}"
#     state: present

# - name: remove the apache package
#   package: name=apache state=absent

    # use: yum
  # with_flattened:
  #   - git
  #   - sudo
  #   - openssh-server

- name: set timezone variables
  copy: content="America/New_York"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
  notify:
    - update-timezone

- name: install supervisor
  become: yes
  package:
    name: supervisor
    state: latest


# - name: Set timezone to {{ timezone }}
#   when: ansible_date_time.tz != '{{ timezone }}'
#   command: timedatectl set-timezone {{ timezone }}
#   tags: tz
