---
# - name: restart php-fpm
#   become: yes
#   supervisorctl:
#     name: php5-fpm
#     state: restarted
#   when: phase == "running"

- name: restart httpd
  become: yes
  supervisorctl:
    name: httpd
    state: restarted
  when: phase == "running"

- name: start httpd
  become: yes
  supervisorctl:
    name: httpd
    state: started
  when: phase == "running"
